TestingOrg/force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestingOrg/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestingOrg/force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

TestingOrg/force-app/main/default/objects/Order__c/fields/Order_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_End_Date__c</fullName>
    <label>Order End Date</label>
    <type>Date</type>
</CustomField>

TestingOrg/force-app/main/default/objects/Order__c/fields/Order_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Start_Date__c</fullName>
    <label>Order Start Date</label>
    <type>Date</type>
</CustomField>

TestingOrg/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Open</fullName>
                <color>#78C953</color>
                <label>Open</label>
            </value>
            <value>
                <fullName>Overdue</fullName>
                <color>#FFCC33</color>
                <label>Overdue</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
                <color>#0B6FCE</color>
                <label>Delivered</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <color>#FF0000</color>
                <label>Canceled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TestingOrg/force-app/main/default/objects/Order__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <summarizedField>Order_Item__c.Total__c</summarizedField>
    <summaryForeignKey>Order_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

TestingOrg/force-app/main/default/objects/Order__c/fields/Weather_Info__c.field-meta.xml
<CustomField>
    <fullName>Weather_Info__c</fullName>
    <label>Weather Info</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

TestingOrg/force-app/main/default/classes/searchOrderController.cls
public with sharing class searchOrderController {
    @auraEnabled(cacheable=true)
    public static list <Order__c> getOrders() {
        return[SELECT Id, Customer__r.Name,Total_Amount__c, Status__c, Order_Start_Date__c ,
                Order_End_Date__c, Weather_Info__c, (SELECT Id, Quantity__c, Unit_Price__c, 
                Total__c From Order_Items__r) FROM Order__c ORDER BY Name];
    }
}